using MedClinic.Application.Interfaces;
using MedClinic.Application.Models.AI;

namespace MedClinic.Infrastructure.AI;

/// <summary>
/// Mock AI provider for development and testing.
/// Returns realistic-looking but fake results.
/// Does NOT call any paid external API.
/// </summary>
public class MockAIProvider : IAIProvider
{
    public string ProviderName => "Mock";

    public Task<MedicalImageAnalysisResult> AnalyzeMedicalImageAsync(
        MedicalImageInput input,
        CancellationToken cancellationToken = default)
    {
        var result = new MedicalImageAnalysisResult(
            Summary: $"[DEMO] Mock AI analysis of {input.FileName}. No real AI processing was performed.",
            Findings: ["No significant findings detected (demo).", "Image quality: acceptable."],
            Observations: ["This is a mock analysis for development and testing purposes."],
            RegionsOfInterest: [],
            Confidence: null,
            RecommendationsForReview: ["Please configure a real AI provider for clinical use."],
            RequiresDoctorReview: true);

        return Task.FromResult(result);
    }

    public Task<LabAnalysisResult> AnalyzeLabResultsAsync(
        LabAnalysisInput input,
        CancellationToken cancellationToken = default)
    {
        var tests = input.Tests.Select(t => new LabTestAnalysis(
            TestName: t.TestName,
            Value: t.Value,
            Unit: t.Unit,
            ReferenceRange: t.ReferenceRange,
            Status: "Normal (Demo)",
            TrendDirection: null,
            Interpretation: "[DEMO] Mock interpretation. Configure a real AI provider for clinical use."
        )).ToList();

        var result = new LabAnalysisResult(
            Summary: "[DEMO] Mock lab analysis. No real AI processing was performed.",
            Tests: tests,
            AbnormalFindings: [],
            TrendObservations: ["This is a mock analysis for development and testing purposes."],
            Recommendations: ["Please configure a real AI provider for clinical use."],
            RequiresDoctorReview: true);

        return Task.FromResult(result);
    }

    public Task<PatientSummaryResult> SummarizePatientAsync(
        PatientSummaryInput input,
        CancellationToken cancellationToken = default)
    {
        var result = new PatientSummaryResult(
            Summary: $"[DEMO] Mock AI summary for patient {input.PatientName}. No real AI processing was performed.",
            KeyFindings: ["Mock finding 1 (demo).", "Mock finding 2 (demo)."],
            ActiveProblems: input.RecentDiagnoses.Take(3).ToList(),
            ImportantAlerts: [],
            SuggestedFollowUp: ["Please configure a real AI provider for clinical use."],
            RequiresDoctorReview: true);

        return Task.FromResult(result);
    }

    public Task<MedicalReportResult> GenerateMedicalReportAsync(
        MedicalReportInput input,
        CancellationToken cancellationToken = default)
    {
        var result = new MedicalReportResult(
            Title: $"[DEMO] {input.ReportType} - Mock Report",
            Content: $"[DEMO] Mock report for {input.PatientName}. This is a demo report generated by MockAIProvider. No real AI processing was performed. Configure a real AI provider for clinical use.",
            Sections: ["Summary (Demo)", "Findings (Demo)", "Recommendations (Demo)"],
            RequiresDoctorReview: true);

        return Task.FromResult(result);
    }

    public Task<AIChatResponse> ChatAsync(
        AIChatRequest request,
        CancellationToken cancellationToken = default)
    {
        var lastMessage = request.Messages.LastOrDefault()?.Content ?? "";
        var response = new AIChatResponse(
            Content: $"[DEMO - MockAIProvider] You said: \"{lastMessage}\".\n\nThis is a demo response. No real AI processing was performed. To enable real AI capabilities, configure an AI provider (OpenAI, Gemini, etc.) in your environment variables.",
            Role: "assistant",
            TokensUsed: null,
            IsError: false);

        return Task.FromResult(response);
    }
}
